### ISSUE TITLE
Running code 

### ISSUE THREAD

**Issue by Abhijithchintu** [Ha0Tang/SelectionGAN#10]
Where should we run this code .In collab and kaggle notebook , we are running out of space , to download data sets ,with given command for pose transfer (person transfer).

**Comment by Ha0Tang** [comment]
sorry, I don't have enough time to implement colab and notebook

**Comment by Abhijithchintu** [comment]
Where did you run this code , is gpu compulsory for this ?

**Comment by Ha0Tang** [comment]
please go to each folder, such as go to [this folder](https://github.com/Ha0Tang/SelectionGAN/tree/master/selectiongan_v1) for our cvpr experiments
