### ISSUE TITLE
question

### ISSUE THREAD

**Issue by haveayoungage** [Ha0Tang/SelectionGAN#13]
Execute code command   --continue_train --which_epoch 35 --epoch_count 36,it comes an error.It can not found _net_D.pth.coule you tell me how to solve it?

**Comment by Ha0Tang** [comment]
Maybe there is no 35_net_D.pth in your saved models.

**Comment by haveayoungage** [comment]
is the _net_D.pth  a file that produce by my training?I do  not konw where it is from

**Comment by haveayoungage** [comment]
could u tell me how to generate the pth file？thanks！

**Comment by Ha0Tang** [comment]
`--continue_train --which_epoch 35 --epoch_count 36` these commands are only used when continuing training, so you should save some models before interrupting training

**Comment by haveayoungage** [comment]
thanks for your time。when i train my model,are there any pars that i need to set to make my train  model saved?
cuz after i can not find my trained model,i only find some results?could u tell me how to work it out?thanks!

**Comment by Ha0Tang** [comment]
please refer to this [line](https://github.com/Ha0Tang/SelectionGAN/blob/e8e15f9e927c79daba338f2e982034c63cf543d1/selectiongan_v1/options/train_options.py#L12)

**Comment by haveayoungage** [comment]
thanks for your time!problem solved!谢谢
