### ISSUE TITLE
hellow!

### ISSUE THREAD

**Issue by HaoDing123** [Ha0Tang/SelectionGAN#2]
Hi! when I run the train,py ,I meet a error :ModuleNotFoundError: No module named 'models.pix2pix_model' . Could you help me ?

**Comment by Ha0Tang** [comment]
What command did you use to run it?

**Comment by HaoDing123** [comment]
Thank you for your reply！
I download the dateset-dayton,and use the command:python train.py --dataroot ./datasets/dayton --name sgan --model selectiongan --which_model_netG unet_256 --which_direction AtoB --dataset_mode aligned --norm batch --gpu_ids 0 --batchSize 16 --niter 50 --niter_decay 50 --loadSize 72 --fineSize 64 --no_flip --lambda_L1 100 --lambda_L1_seg 1 --display_winsize 64 --display_id 0.
Result:AssertionError: ./datasets/dayton/train is not a valid directory

**Comment by Ha0Tang** [comment]
Try this one:
`python train.py --dataroot ./datasets/dayton --name sgan --model selectiongan --which_model_netG unet_256 --which_direction AtoB --dataset_mode aligned --norm batch --gpu_ids 0 --batchSize 4 --loadSize 286 --fineSize 256 --no_flip --lambda_L1 100 --lambda_L1_seg 1 --display_id 0`

and double-check your folder `./datasets/dayton`.

**Comment by HaoDing123** [comment]
I have tried it,but come across the same error. The folder ./datasets/dayton is full of images which is downloaded from http://www.mediafire.com/file/k01laql4bz5r7x5/dayton.zip/file.
I also think it's a problem with this folder. Have you done anything else with this folder?

**Comment by Ha0Tang** [comment]
Can you run this first:
`python train.py --dataroot ./datasets/samples/dayton/ --name sgan --model selectiongan --which_model_netG unet_256 --which_direction AtoB --dataset_mode aligned --norm batch --gpu_ids 0 --batchSize 1 --loadSize 286 --fineSize 256 --no_flip --lambda_L1 100 --lambda_L1_seg 1 --display_id 0`
let me know if this ok?

**Comment by HaoDing123** [comment]
Hello，it doesn't work. There is no folder under dayton. it only have a lot of images.

**Comment by Ha0Tang** [comment]
It works now, can you try again?

**Comment by HaoDing123** [comment]
It' ok! Thank you very much!
