### ISSUE TITLE
sharpness difference

### ISSUE THREAD

**Issue by hluo29** [Ha0Tang/SelectionGAN#3]
Hello, could you provide the sharpness difference evaluation code? Thanks

**Comment by Ha0Tang** [comment]
Please refer here https://github.com/Ha0Tang/SelectionGAN/blob/master/scripts/evaluation/compute_ssim_psnr_sharpness.lua

**Comment by hluo29** [comment]
Thanks a lot.

**Comment by hluo29** [comment]
In the paper, you mean 'C outperforms A with 8.19, F outperforms E with 4.67 on ssim', actually they are 0.0819 and 0.0467. How to understand?

**Comment by Ha0Tang** [comment]
It means Baseline F outperforms E with around 4.67 **points** gain on the SSIM metric. In other words, you can multiply each value by 100.

**Comment by hluo29** [comment]
ok, thanks
