### ISSUE TITLE
Can't download the dataset by scripts

### ISSUE THREAD

**Issue by 4ever-Rain** [Ha0Tang/SelectionGAN#4]
Hello. I have used `sh download_selectiongan_dataset.sh` to download the dataset but the URLs seem to brokedown with `ERROR 404: Not Found`.

**Comment by Ha0Tang** [comment]
Which dataset did you want to download?

**Comment by 4ever-Rain** [comment]
Ego2Top Dataset. 
This dataset was uploaded on dropbox. I can't download it in China. So I want to try your scripts.

**Comment by Ha0Tang** [comment]
Sorry about this, we do not provide the download of the Ego2top dataset. You need to download it from the dropbox.

**Comment by 4ever-Rain** [comment]
OK. Thank you!

**Comment by Ha0Tang** [comment]
@4ever-Rain `sh download_selectiongan_dataset.sh` is working now. Please refer to the `readme` for more details.

**Comment by 4ever-Rain** [comment]
Thank you！~
