### ISSUE TITLE
self.padding, self.dilation, self.groups) RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by GANGREEK** [Ha0Tang/SelectionGAN#5]
self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

**Comment by Ha0Tang** [comment]
Are you using PyTorch 0.4.1 ?
