### ISSUE TITLE
inception score

### ISSUE THREAD

**Issue by 04lm40** [Ha0Tang/SelectionGAN#7]
Hello, I trained a model on the CVUSA dataset, but the IS value and KL result are slightly worse during the evaluation. The following are my running commands. Are there any problems that I have not noticed?
python train.py --dataroot ./datasets/cvusa/ \
--name cvusa_selectiongan \
--model selectiongan \
--which_model_netG unet_256 \
--which_direction AtoB \
--dataset_mode aligned \
--norm batch \
--gpu_ids 0,1 \
--batchSize 4 \
--loadSize 286 \
--fineSize 256 \
--no_flip \
--display_id 1 \
--lambda_L1 100 \
--lambda_L1_seg 1

**Comment by Ha0Tang** [comment]
What are your results? Did you use two GPUs for training?

**Comment by 04lm40** [comment]
IS：3.5 2.65 3.59  KL：3.12.
Yes, I used two GPUs.

**Comment by Ha0Tang** [comment]
The results in our paper were generated using one GPU.

**Comment by 04lm40** [comment]
Thank you!
