### ISSUE TITLE
How to evaluate your model, where is the code of metrics 

### ISSUE THREAD

**Issue by sunshinewhy** [Ha0Tang/SelectionGAN#8]
Excuse me. Could you tell me how to get the scores of these metrics in your paper?
Such as: SSIM, IS, PSNR, DS, FID scores
![image](https://user-images.githubusercontent.com/43949229/91463394-ed8b1700-e8bd-11ea-9f8f-1904ca9c8188.png)
Thanks!

**Comment by Ha0Tang** [comment]
All evaluation codes are provided [here](https://github.com/Ha0Tang/SelectionGAN/tree/master/selectiongan_v1#evaluation-code). Have you tried these codes?
