### ISSUE TITLE
a question about the equation(3) in your tpami submission

### ISSUE THREAD

**Issue by Zijian007** [Ha0Tang/SelectionGAN#9]
what does the paramater “j” mean？

**Comment by Ha0Tang** [comment]
As stated in our paper, each pixel A_{ji} in A measures the i-th channel’s impact on the j-th channel.

**Comment by Zijian007** [comment]
Is F_{mi} the i-th channel of F_{m}?

**Comment by Ha0Tang** [comment]
Yes.

**Comment by Ha0Tang** [comment]
will close this issue, if you have any questions, please open a new one.

**Comment by Zijian007** [comment]
I think that F'_{m} should be F'_{mj}

**Comment by Ha0Tang** [comment]
You are right, will fix it in the next version, thanks
